
Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"
  config.vm.network "private_network", ip: "192.168.33.22"
  config.vm.hostname = "ansible-master"
  
  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

 config.vm.synced_folder ".", "/vagrant", type: "virtualbox"
  
 config.vm.provider "virtualbox" do |vb|

   # Customize the amount of memory on the VM:
   vb.memory = "1024"
 end

  config.vm.provision "shell", inline: <<-SHELL
    sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
    systemctl restart sshd
	yum install -y git curl htop vim net-tools
	yum install -y epel-release
	yum install -y ansible
  SHELL
end
